title: Zachary C. Brown
logo: /assets/img/logo.png
description: Zachary is an Machine Learning Researcher and Electrical Engineering PhD Student at Duke University.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
